
name: Update Docker Hub Description
on:
  push:
    branches:
      - master
    paths:
      - README.rst
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: charlocharlie
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: charlocharlie/autotorrent
        readme-filepath: ./README.rst